### ISSUE TITLE
Add integration to guidance library

### ISSUE THREAD

**Issue by paolorechia** [kyegomez/tree-of-thoughts#11]
Thanks a lot for implementing this ToT library, nice work!

I think it could benefit a lot from using Microsoft Guidance (https://github.com/microsoft/guidance), specially with smaller local models that have a hard time following the instructions exactly.

Is this something you would be interested in? 

Sadly, I’m low on time this week (and the next) to help with the implementation, but I would eventually look into making this integration (if you have no interest in making it yourself).

**Comment by yhyu13** [comment]
tutorial : https://github.com/microsoft/guidance/blob/main/notebooks/tutorial.ipynb

**Comment by yhyu13** [comment]
@paolorechia Guidance actually supports loading local LLMs and its pretty versatile https://github.com/microsoft/guidance/blob/main/guidance/llms/transformers/_llama.py, but loading local LLMs will surely making ToT heavier. 

I believe you can extend from that llm class a little bit wrapping your webui API call inside, this way,  your pr would work with guidance.

**Comment by paolorechia** [comment]
@yhyu13 thanks for looking into it :)

I already have a fork of guidance that uses the text-generation-web-ui api: https://github.com/paolorechia/local-guidance

I didn’t mention it before I was not sure if you wanted an integration to text-generation-web-ui in the first place.

I did something similar as you mention, but based on OpenAI class. Main problem here is that my code doesn’t support many features of guidance, but that’s definitely a way to go.

Maybe something better would be to stick to the more “official” integrations, like Huggingface, so it also supports better guidance?

**Comment by paolorechia** [comment]
@yhyu13 Not part of, but you'll get a much better support to use guidance if you use Hugging Face. There are several features implemented specifically for the HF API, e.g., token healing.

**Comment by yhyu13** [comment]
I thought token healing was just an bool flag, had never looked inside. Will do

**Comment by kyegomez** [comment]
Trying to implement guidance right now can you all help!, I'm making an all-new folder at extremely_experimental

**Comment by kyegomez** [comment]
Nevermind just saw your pr

**Comment by kyegomez** [comment]
Now we need to update the prompts of the models to use guidance

**Comment by kyegomez** [comment]
@yhyu13 

Given the current state of reasoning: 'Given the current state of reasoning: 'W h a t   a r e   n e x t   g e n e r a t i o n   r e a s o n i n g   m e t h o d s   f o r   L a r g e   L a n g u a g e   M o d e l s', generate {5} coherent thoughts to continue the reasoning process:', evaluate its value as a float between 0 and 1, and NOTHING ELSE:
Error parsing value: Given the current state of reasoning: 'Given the current state of reasoning: 'W h a t   a r e   n e x t   g e n e r a t i o n   r e a s o n i n g   m e t h o d s   f o r   L a r g e   L a n g u a g e   M o d e l s', generate {5} coherent thoughts to continue the reasoning process:', evaluate its value as a float between 0 and 1, and NOTHING ELSE:
Solution: None
Traceback (most recent call last):
  File "<ipython-input-13-7c9b024fdbb6>", line 263, in evaluate_states
    value = float(value_text)
ValueError: could not convert string to float: "Given the current state of reasoning: 'Given the current state of reasoning: 'W h a t   a r e   n e x t   g e n e r a t i o n   r e a s o n i n g   m e t h o d s   f o r   L a r g e   L a n g u a g e   M o d e l s', generate {5} coherent thoughts to continue the reasoning process:', evaluate its value as a float between 0 and 1, and NOTHING ELSE:"

**Comment by jabowery** [comment]
```
:~/dev/tree-of-thoughts$ python example.py 
...
ModuleNotFoundError: No module named 'guidance'

```

**Comment by kyegomez** [comment]
tree-of-thoughts % /usr/local/bin/python3 /Users/defalt/Desktop/Athena/research/tree-of-thoughts/experiements/extremely_experimental/prompting/guidancePrompt.py
Using api_model text-davinci-003
Generated thoughts: Given the current state of reasoning: '{state_text}', generate {5} coherent thoughts to continue the reasoning process:{#each (gen 'thoughts' k=k)}
{this}{/each}
Traceback (most recent call last):
  File "/Users/defalt/Desktop/Athena/research/tree-of-thoughts/experiements/extremely_experimental/prompting/guidancePrompt.py", line 434, in <module>
    solution = tree_of_thoughts.solve(input_problem, k, T, b, vth, timeout, confidence_threshold=confidence, max_iterations=max_iterations, convergence_threshold=convergence_threshold, convergence_count=convergence_count)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/defalt/Desktop/Athena/research/tree-of-thoughts/experiements/extremely_experimental/prompting/guidancePrompt.py", line 401, in solve
    result = self.tot_dfs(x, k, T, vth, confidence_threshold=confidence_threshold, max_iterations=max_iterations, convergence_threshold=convergence_threshold, convergence_count=convergence_count)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/defalt/Desktop/Athena/research/tree-of-thoughts/experiements/extremely_experimental/prompting/guidancePrompt.py", line 387, in tot_dfs
    dfs(x, 1)
  File "/Users/defalt/Desktop/Athena/research/tree-of-thoughts/experiements/extremely_experimental/prompting/guidancePrompt.py", line 379, in dfs
    for s_prime in sorted(self.model.generate_thoughts(s, k)):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/guidance/_program.py", line 326, in __getitem__
    return self._variables[key]
           ~~~~~~~~~~~~~~~^^^^^
KeyError: 0

**Comment by paolorechia** [comment]
@jabowery is that using guidance?

**Comment by jabowery** [comment]
> is that using guidance?

Almost certainly.  The only way I was able to get the `example.py` program to run was to include `guidance` in my `conda` environment via the provided `environment.yml` because without `guidance` installed, `example.py` would fail with `ModuleNotFoundError: No module named 'guidance'`

**Comment by jellederijke** [comment]
I have the same issue. Running the example prompted me to install guidance. After pip installing guidance and using this as the input_problem: using 1 2 6 9 us these numbers and basic arithmetic operations (+-*/) to obtain 24. The output should be an equation. I get some response like solution: (['Observation: All of the numbers provided can be combined to create 24.\nThoughts: We can use trial and error to find the combination of numbers and operations that produces the desired result of 24.'], 1.0)

Any ideas on how (with what settings) to get the example going are highly appreciated :)

**Comment by yhyu13** [comment]
@ALL https://github.com/kyegomez/tree-of-thoughts/pull/18/#issue-1723812572 guidance is still WIP at this moment, the prompt suggested from https://github.com/microsoft/guidance that uses system, user, assistant actually leads to GPT4 spitting out wrong output for evaluation

The example.py will not use guidance before this problem is fixed

**Comment by yhyu13** [comment]
https://github.com/kyegomez/tree-of-thoughts/issues/11#issuecomment-1560042264 @jabowery 

text-davinci-003 is poor at this task, gpt4 and chatgpt mostly will speculate with actual mathematics formula

**Comment by jellederijke** [comment]
I have finally managed to solve this puzzle:
    input_problem = "use 1 2 3 as available numbers, you can only use each number once and basic arithmetic operations (+-*/) to obtain 7. The output should be an equation."

with gpt-4 and V2 in the example file with these settings:
k = 5
    T = 2
    b = 3
    vth = 0.5
    timeout = 20
    confidence = 1.0 #cmodel is confident on performance
    max_iterations = 40 #tree branh nodes 
    convergence_threshold = 0.01
    convergence_count = 5

search_algorithm = "BFS"

#cot or propose
strategy="cot"

# value or vote
evaluation_strategy = "value"

Pretty awesome! Did cost quite a lot of tokens, though.
