### ISSUE TITLE
ModuleNotFoundError: No module named 'dotenv'

### ISSUE THREAD

**Issue by moisesdiaz-ds** [kyegomez/tree-of-thoughts#37]
ModuleNotFoundError: No module named 'dotenv'

pip install dotenv does not work, any ideas?

**Comment by geeknik** [comment]
`sudo apt-get install python3-dotenv python3-dotenv-cli` solved it for me on ubuntu.

**Comment by vumg-z** [comment]
https://stackoverflow.com/questions/49328525/pip-install-dotenv-error-code-1-windows-10

as geeknik pointed out, you should install python3-dotenv and it will work

**Comment by wqw547243068** [comment]
Same problem too, installation failed in Mac, error message:

```sh
TQV9MF4NXR:tree-of-thoughts bytedance$ pip install dotenv
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting dotenv
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/e2/46/3754073706e31670eed18bfa8a879305b56a471db15f20523c2427b10078/dotenv-0.0.5.tar.gz (2.4 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install backend dependencies did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
      Collecting distribute
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/5f/ad/1fde06877a8d7d5c9b60eff7de2d452f639916ae1d48f0b8f97bf97e570a/distribute-0.7.3.zip (145 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Preparing metadata (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [6 lines of output]
            usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
               or: setup.py --help [cmd1 cmd2 ...]
               or: setup.py --help-commands
               or: setup.py cmd --help
      
            error: invalid command 'dist_info'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
      
      × Encountered error while generating package metadata.
      ╰─> See above for output.
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by alex-coch** [comment]
The same on ubuntu 22.04.:
`pip install tree_of_thoughts
Collecting tree_of_thoughts
  Using cached tree_of_thoughts-0.2.7-py3-none-any.whl (14 kB)
Collecting guidance (from tree_of_thoughts)
  Using cached guidance-0.0.57-py3-none-any.whl (83 kB)
Collecting openai (from tree_of_thoughts)
  Using cached openai-0.10.5.tar.gz (157 kB)
  Preparing metadata (setup.py) ... done
Collecting transformers (from tree_of_thoughts)
  Using cached transformers-4.29.2-py3-none-any.whl (7.1 MB)
Collecting dotenv (from tree_of_thoughts)
  Using cached dotenv-0.0.5.tar.gz (2.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [76 lines of output]
        error: subprocess-exited-with-error
      
        × python setup.py egg_info did not run successfully.
        │ exit code: 1
        ╰─> [16 lines of output]
            Traceback (most recent call last):
              File "<string>", line 36, in <module>
              File "<pip-setuptools-caller>", line 14, in <module>
              File "/tmp/pip-wheel-ajo68hru/distribute_820e4f5102b14a1ca9546b69347c1dd2/setuptools/__init__.py", line 2, in <module>
                from setuptools.extension import Extension, Library
              File "/tmp/pip-wheel-ajo68hru/distribute_820e4f5102b14a1ca9546b69347c1dd2/setuptools/extension.py", line 5, in <module>
                from setuptools.dist import _get_unpatched
              File "/tmp/pip-wheel-ajo68hru/distribute_820e4f5102b14a1ca9546b69347c1dd2/setuptools/dist.py", line 7, in <module>
                from setuptools.command.install import install
              File "/tmp/pip-wheel-ajo68hru/distribute_820e4f5102b14a1ca9546b69347c1dd2/setuptools/command/__init__.py", line 8, in <module>
                from setuptools.command import install_scripts
              File "/tmp/pip-wheel-ajo68hru/distribute_820e4f5102b14a1ca9546b69347c1dd2/setuptools/command/install_scripts.py", line 3, in <module>
                from pkg_resources import Distribution, PathMetadata, ensure_directory
              File "/tmp/pip-wheel-ajo68hru/distribute_820e4f5102b14a1ca9546b69347c1dd2/pkg_resources.py", line 1518, in <module>
                register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
            AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
      
      × Encountered error while generating package metadata.
      ╰─> See above for output.
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      /home/alex/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      Traceback (most recent call last):
        File "/home/alex/anaconda3/lib/python3.7/site-packages/setuptools/installer.py", line 96, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "/home/alex/anaconda3/lib/python3.7/subprocess.py", line 328, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/home/alex/anaconda3/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmplwctifoy', '--quiet', 'distribute']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ij6vqdkj/dotenv_780d97381bfa43ca8e1495c0012f98e3/setup.py", line 23, in <module>
          scripts=['scripts/dotenv']
        File "/home/alex/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 106, in setup
          _install_setup_requires(attrs)
        File "/home/alex/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 79, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/home/alex/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 84, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/home/alex/anaconda3/lib/python3.7/site-packages/setuptools/dist.py", line 917, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/home/alex/anaconda3/lib/python3.7/site-packages/setuptools/installer.py", line 41, in _fetch_build_eggs
          replace_conflicting=True,
        File "/home/alex/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 828, in resolve
          req, best, replace_conflicting, env, installer, required_by, to_activate
        File "/home/alex/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 864, in _resolve_dist
          req, ws, installer, replace_conflicting=replace_conflicting
        File "/home/alex/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1133, in best_match
          return self.obtain(req, installer)
        File "/home/alex/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1145, in obtain
          return installer(requirement)
        File "/home/alex/anaconda3/lib/python3.7/site-packages/setuptools/installer.py", line 98, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/home/alex/anaconda3/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmplwctifoy', '--quiet', 'distribute']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`
